name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      # run tests on all versions, even if one fails
      fail-fast: false
      matrix:
        # add any other Typst versions that your package should support
        typst-version:
          - typst: 0.14
            tytanic: 0.3
            # the docs don't need to build with all versions supported by the package;
            # the latest one is enough
            doc: true

    name: Test for ${{ matrix.typst-version.typst }} (Tytanic ${{ matrix.typst-version.tytanic }}${{ matrix.typst-version.doc && ', with docs' }})
    runs-on: node-stable

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup typst
        id: setup-typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: ${{ matrix.typst-version.typst }}

      - name: Setup zudrell.eu package registry
        uses: ./.gitea/setup-private-registry/
        with:
          repository: ${{ REGISTRY_REPO }}
          token: ${{ secrets.TYPST_PACKAGE_REPO_TOKEN }}
          namespace: zudrell.eu

      - name: Setup tytanic
        uses: typst-community/setup-tytanic@v1
        with:
          github-token: ${{ secrets.TYPST_GITHUB_TOKEN }}
          tytanic-version: ${{ matrix.typst-version.tytanic }}

      - name: Run test suite
        run: just test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: typst-${{ steps.setup-typst.outputs.typst-version }}-test-results
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5

      - name: Build docs
        if: ${{ matrix.typst-version.doc }}
        run: just doc
